---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        - id: check-yaml
        - id: check-merge-conflict
        - id: debug-statements
        - id: end-of-file-fixer
        - id: mixed-line-ending
        - id: trailing-whitespace
        - id: check-added-large-files
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
        - id: shellcheck
    - repo: https://github.com/markdownlint/markdownlint/
      rev: v0.12.0
      hooks:
        - id: markdownlint
    # We must run this locally to capture the .cu files
    - repo: local
      hooks:
      - id: clang-format-local
        name: clang-format
        entry: clang-format -i -style=Google
        language: system
        files: '\.(cpp|hpp|cc|cxx|c|h|cu|cuh)$'
    - repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.3.5
      hooks:
        - id: clang-tidy
          args:
            - "--extra-arg=-std=c++17"
            - "--extra-arg=-I/usr/local/cuda-12.3/include"
            - "--extra-arg=-I/usr/include/opencv4"
        - id: cppcheck
          args:
            - "--inline-suppr"  # Enable inline suppression
            - "--suppress=missingInclude"  # Do not check 3rd party includes
        - id: cpplint
          args: ["--filter=-legal/copyright,-build/include_order,-whitespace/comments,-readability/todo,-readability/casting,-build/include_subdir"]
        - id: include-what-you-use
          files: '\.(cpp|hpp|cc|cxx|c|h|cu)$'
          args:
            - "-Xiwyu"  # Xiwyu comes before iwyu arguments
            - "--mapping_file=.linters/iwyu.imp"
            - "-Xiwyu"
            - "--update_comments"
            - "-std=c++17" # This is a clang argument as it's not preceded by iwyu
            - "-I/usr/local/cuda-12.3/include"
            - "-I/usr/include/opencv4"
